PROJECT = ../../..
TARGETS =
TARGETS += vexcl-compute-test

VEXCL		= $(PROJECT)/3rdparty/vexcl
CXXFLAGS	+= -I$(VEXCL)
# CXXFLAGS	+= -Wno-unused-local-typedefs
# CXXFLAGS	+= -Wno-unused-variable

include $(PROJECT)/include.mk
