# follows GLASSWING_ROOT

#defines:
#- GLASSWING_INCLUDE_DIRS
#- GLASSWING_LIBRARIES

FIND_PACKAGE(PackageHandleStandardArgs)

if (DEFINED ENV{GLASSWING_ROOT})
	set(GLASSWING_ROOT "$ENV{GLASSWING_ROOT}")
endif()

find_path(GLASSWING_INCLUDE_DIRS glasswing/glasswing.h
  PATHS "${GLASSWING_ROOT}"
  PATH_SUFFIXES include
)

find_library(GLASSWING_LIB NAMES glasswing
  PATHS ${GLASSWING_ROOT}
  PATH_SUFFIXES lib libs
)
find_library(GLASSWING_NET_LIB NAMES glasswing-net
  PATHS ${GLASSWING_ROOT}
  PATH_SUFFIXES lib libs
)
find_library(GLASSWING_CLPP_LIB NAMES clpp
  PATHS ${GLASSWING_ROOT}
  PATH_SUFFIXES lib libs
)

SET(GLASSWING_LIBRARIES "${GLASSWING_LIB};${GLASSWING_NET_LIB};${GLASSWING_CLPP_LIB}")

find_package_handle_standard_args(GLASSWING DEFAULT_MSG
    GLASSWING_INCLUDE_DIRS GLASSWING_LIBRARIES)
